---
dependency:
  name: galaxy
driver:
  name: vagrant
  provider:
    # Can be any supported provider (virtualbox, parallels, libvirt, etc)
    name: virtualbox
platforms:
  - name: centos8
    box: generic/centos8
    memory: 2048
    cpus: 2
    interfaces:
      - network_name: forwarded_port
        guest: 80
        host: 8080
        auto_correct: true
provisioner:
  name: ansible
verifier:
  name: testinfra
